### ISSUE TITLE
enhacement: update event status

### ISSUE THREAD

**Issue by marianamartineza** [Kunaisoft-Team/Severin_Push_Hands_Backend_API#110]
Scenario:
It is necessary to be able to change the status of the event directly with the path of the organization and the id of the event

GIVEN:
When you create or edit an event you can change its status

WHEN:
But it is also necessary to send the other attributes of the event

THEN:
The status of the event should be able to be changed directly only with the event id and the organization path.

solution:
Create a new put request to update the event status

**Comment by davidurosa** [comment]
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/63787679/9edb6133-5d5f-4efc-b15f-de4b8d9abf69)
![image](https://github.com/Kunaisoft-Team/Severin_Push_Hands_Backend_API/assets/63787679/297fbb2d-1c96-464c-80e9-98470be0b785)
A validation was added if the event has a start date less than the current one, it will not be published separately, you must send a numerical status and send all the required fields, otherwise the event will not be published
